[package]
name = "compiler_rs"
version = "0.1.0"
authors = ["l-const <const_l@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
